from PyQt5.QtCore import *
from PyQt5 import QtWidgets, uic
from messagebox import msg_error, msg_about
import pymysql as sql
import db
from PyQt5.QtWidgets import *
import datetime
from fpdf import *

app = QtWidgets.QApplication([])


login = uic.loadUi("untitled.ui")
registro = uic.loadUi("registro.ui")
registro_tutor = uic.loadUi("registro_profesor.ui")
entrar= uic.loadUi("entrar.ui")
entrar_tutor= uic.loadUi("entrar_tutor.ui")

db=db.Database()

def gui_login():
    correo = login.lineEdit.text()
    password = login.lineEdit_2.text()

    if len(correo) == 0 or len(password)==0:
        login.label_4.setText("Ingrese todos los datos")
    else:
        rs=db.login_alumno(correo, password) 
        if rs:
            msg_about("","Se pudo iniciar sesión con éxito")
            gui_entrar(rs)
        else:
            rs=db.login_tutor(correo, password)
            if rs:
                msg_about("","Se pudo iniciar sesión con éxito")
                gui_entrar_tutor(rs)
            else:
                login.label_4.setText("Correo o contraseña incorrectos")

def gui_registro_alumno():
    login.hide()
    registro.show()

def cerrar_sesion():
    entrar.close()
    entrar_tutor.close()
    login.lineEdit.setText("")
    login.lineEdit_2.setText("")
    login.show()
    msg_about("", "Sesión cerrada")

def gui_entrar(result):
    login.hide()
    entrar.show()
    entrar.label.setText(("Bienvenido alumno "+result[1]+" "+result[2]+"-"+result[5]).upper())
    rs_reporte=db.mostrar_reportes(result[0])
    row=0
    while(row<len(rs_reporte)):
        entrar.tableWidget_2.insertRow(row)
        numero=QTableWidgetItem(str(row+1))
        comentario=QTableWidgetItem(str(rs_reporte[row][1]))
        fecha= QTableWidgetItem(str(rs_reporte[row][2]))
        entrar.tableWidget_2.setItem(row,0,numero)
        entrar.tableWidget_2.setItem(row,1,comentario)
        entrar.tableWidget_2.setItem(row,2,fecha)
        row+=1
    
    rs_nota_mate=db.mostrar_notas(result[0],"Matemática")
    rs_nota_ed=db.mostrar_notas(result[0],"Educación Física")
    rs_nota_tuto=db.mostrar_notas(result[0],"Tutoría")
    rs_nota_comu=db.mostrar_notas(result[0],"Comunicación")
    rs_nota_cien=db.mostrar_notas(result[0],"Ciencias")
    mostrar_nota_mate(rs_nota_mate)
    mostrar_nota_ed(rs_nota_ed)
    mostrar_nota_tuto(rs_nota_tuto)
    mostrar_nota_comu(rs_nota_comu)
    mostrar_nota_cien(rs_nota_cien)
    entrar.pushButton_6.clicked.connect(imprimir_notas)

# NO ABRIR XD
def mostrar_nota_mate(rs_nota):
    row=0
    while(row<4):
        tarea_b1=QTableWidgetItem(str(rs_nota[1]))
        tarea_b2=QTableWidgetItem(str(rs_nota[2]))
        tarea_b3= QTableWidgetItem(str(rs_nota[3]))
        tarea_b4= QTableWidgetItem(str(rs_nota[4]))
        bimestre1= QTableWidgetItem(str(rs_nota[5]))
        bimestre2= QTableWidgetItem(str(rs_nota[6]))
        bimestre3= QTableWidgetItem(str(rs_nota[7]))
        bimestre4= QTableWidgetItem(str(rs_nota[8]))
        parcial_b1= QTableWidgetItem(str(rs_nota[9]))
        parcial_b2= QTableWidgetItem(str(rs_nota[10]))
        parcial_b3= QTableWidgetItem(str(rs_nota[11]))
        parcial_b4= QTableWidgetItem(str(rs_nota[12]))
        prom1=(str(round(int((rs_nota[1]+rs_nota[5]+rs_nota[9])/3))))
        prom2=(str(round(int((rs_nota[2]+rs_nota[6]+rs_nota[10])/3))))
        prom3=(str(round(int((rs_nota[3]+rs_nota[7]+rs_nota[11])/3))))
        prom4=(str(round(int((rs_nota[4]+rs_nota[8]+rs_nota[12])/3))))
        entrar.tableWidget_3.setItem(0,0,tarea_b1)
        entrar.tableWidget_3.setItem(0,1,tarea_b2)
        entrar.tableWidget_3.setItem(0,2,tarea_b3)
        entrar.tableWidget_3.setItem(0,3,tarea_b4)
        entrar.tableWidget_3.setItem(1,0,parcial_b1)
        entrar.tableWidget_3.setItem(1,1,parcial_b2)
        entrar.tableWidget_3.setItem(1,2,parcial_b3)
        entrar.tableWidget_3.setItem(1,3,parcial_b4)
        entrar.tableWidget_3.setItem(2,0,bimestre1)
        entrar.tableWidget_3.setItem(2,1,bimestre2)
        entrar.tableWidget_3.setItem(2,2,bimestre3)
        entrar.tableWidget_3.setItem(2,3,bimestre4)
        entrar.tableWidget_3.setItem(2,3,bimestre4)
        entrar.tableWidget_3.setItem(2,3,bimestre4)
        entrar.tableWidget_3.setItem(2,3,bimestre4)
        entrar.tableWidget_3.setItem(2,3,bimestre4)
        entrar.tableWidget_3.setItem(2,3,bimestre4)
        entrar.tableWidget_3.setItem(3,0,QTableWidgetItem(prom1))
        entrar.tableWidget_3.setItem(3,1,QTableWidgetItem(prom2))
        entrar.tableWidget_3.setItem(3,2,QTableWidgetItem(prom3))
        entrar.tableWidget_3.setItem(3,3,QTableWidgetItem(prom4))
        entrar.tableWidget_3.setItem(3,4,QTableWidgetItem(str(round((int(prom1)+int(prom2)+int(prom3)+int(prom4))/4))))
        row+=1
def mostrar_nota_ed(rs_nota):
    row=0
    while(row<4):
        tarea_b1=QTableWidgetItem(str(rs_nota[1]))
        tarea_b2=QTableWidgetItem(str(rs_nota[2]))
        tarea_b3= QTableWidgetItem(str(rs_nota[3]))
        tarea_b4= QTableWidgetItem(str(rs_nota[4]))
        bimestre1= QTableWidgetItem(str(rs_nota[5]))
        bimestre2= QTableWidgetItem(str(rs_nota[6]))
        bimestre3= QTableWidgetItem(str(rs_nota[7]))
        bimestre4= QTableWidgetItem(str(rs_nota[8]))
        parcial_b1= QTableWidgetItem(str(rs_nota[9]))
        parcial_b2= QTableWidgetItem(str(rs_nota[10]))
        parcial_b3= QTableWidgetItem(str(rs_nota[11]))
        parcial_b4= QTableWidgetItem(str(rs_nota[12]))
        prom1=(str(round(int((rs_nota[1]+rs_nota[5]+rs_nota[9])/3))))
        prom2=(str(round(int((rs_nota[2]+rs_nota[6]+rs_nota[10])/3))))
        prom3=(str(round(int((rs_nota[3]+rs_nota[7]+rs_nota[11])/3))))
        prom4=(str(round(int((rs_nota[4]+rs_nota[8]+rs_nota[12])/3))))
        entrar.tableWidget_6.setItem(0,0,tarea_b1)
        entrar.tableWidget_6.setItem(0,1,tarea_b2)
        entrar.tableWidget_6.setItem(0,2,tarea_b3)
        entrar.tableWidget_6.setItem(0,3,tarea_b4)
        entrar.tableWidget_6.setItem(1,0,parcial_b1)
        entrar.tableWidget_6.setItem(1,1,parcial_b2)
        entrar.tableWidget_6.setItem(1,2,parcial_b3)
        entrar.tableWidget_6.setItem(1,3,parcial_b4)
        entrar.tableWidget_6.setItem(2,0,bimestre1)
        entrar.tableWidget_6.setItem(2,1,bimestre2)
        entrar.tableWidget_6.setItem(2,2,bimestre3)
        entrar.tableWidget_6.setItem(2,3,bimestre4)
        entrar.tableWidget_6.setItem(2,3,bimestre4)
        entrar.tableWidget_6.setItem(2,3,bimestre4)
        entrar.tableWidget_6.setItem(2,3,bimestre4)
        entrar.tableWidget_6.setItem(2,3,bimestre4)
        entrar.tableWidget_6.setItem(2,3,bimestre4)
        entrar.tableWidget_6.setItem(3,0,QTableWidgetItem(prom1))
        entrar.tableWidget_6.setItem(3,1,QTableWidgetItem(prom2))
        entrar.tableWidget_6.setItem(3,2,QTableWidgetItem(prom3))
        entrar.tableWidget_6.setItem(3,3,QTableWidgetItem(prom4))
        entrar.tableWidget_6.setItem(3,4,QTableWidgetItem(str(round((int(prom1)+int(prom2)+int(prom3)+int(prom4))/4))))
        row+=1
def mostrar_nota_tuto(rs_nota):
    row=0
    while(row<4):
        tarea_b1=QTableWidgetItem(str(rs_nota[1]))
        tarea_b2=QTableWidgetItem(str(rs_nota[2]))
        tarea_b3= QTableWidgetItem(str(rs_nota[3]))
        tarea_b4= QTableWidgetItem(str(rs_nota[4]))
        bimestre1= QTableWidgetItem(str(rs_nota[5]))
        bimestre2= QTableWidgetItem(str(rs_nota[6]))
        bimestre3= QTableWidgetItem(str(rs_nota[7]))
        bimestre4= QTableWidgetItem(str(rs_nota[8]))
        parcial_b1= QTableWidgetItem(str(rs_nota[9]))
        parcial_b2= QTableWidgetItem(str(rs_nota[10]))
        parcial_b3= QTableWidgetItem(str(rs_nota[11]))
        parcial_b4= QTableWidgetItem(str(rs_nota[12]))
        prom1=(str(round(int((rs_nota[1]+rs_nota[5]+rs_nota[9])/3))))
        prom2=(str(round(int((rs_nota[2]+rs_nota[6]+rs_nota[10])/3))))
        prom3=(str(round(int((rs_nota[3]+rs_nota[7]+rs_nota[11])/3))))
        prom4=(str(round(int((rs_nota[4]+rs_nota[8]+rs_nota[12])/3))))
        entrar.tableWidget_7.setItem(0,0,tarea_b1)
        entrar.tableWidget_7.setItem(0,1,tarea_b2)
        entrar.tableWidget_7.setItem(0,2,tarea_b3)
        entrar.tableWidget_7.setItem(0,3,tarea_b4)
        entrar.tableWidget_7.setItem(1,0,parcial_b1)
        entrar.tableWidget_7.setItem(1,1,parcial_b2)
        entrar.tableWidget_7.setItem(1,2,parcial_b3)
        entrar.tableWidget_7.setItem(1,3,parcial_b4)
        entrar.tableWidget_7.setItem(2,0,bimestre1)
        entrar.tableWidget_7.setItem(2,1,bimestre2)
        entrar.tableWidget_7.setItem(2,2,bimestre3)
        entrar.tableWidget_7.setItem(2,3,bimestre4)
        entrar.tableWidget_7.setItem(2,3,bimestre4)
        entrar.tableWidget_7.setItem(2,3,bimestre4)
        entrar.tableWidget_7.setItem(2,3,bimestre4)
        entrar.tableWidget_7.setItem(2,3,bimestre4)
        entrar.tableWidget_7.setItem(2,3,bimestre4)
        entrar.tableWidget_7.setItem(3,0,QTableWidgetItem(prom1))
        entrar.tableWidget_7.setItem(3,1,QTableWidgetItem(prom2))
        entrar.tableWidget_7.setItem(3,2,QTableWidgetItem(prom3))
        entrar.tableWidget_7.setItem(3,3,QTableWidgetItem(prom4))
        entrar.tableWidget_7.setItem(3,4,QTableWidgetItem(str(round((int(prom1)+int(prom2)+int(prom3)+int(prom4))/4))))
        row+=1
def mostrar_nota_comu(rs_nota):
    row=0
    while(row<4):
        tarea_b1=QTableWidgetItem(str(rs_nota[1]))
        tarea_b2=QTableWidgetItem(str(rs_nota[2]))
        tarea_b3= QTableWidgetItem(str(rs_nota[3]))
        tarea_b4= QTableWidgetItem(str(rs_nota[4]))
        bimestre1= QTableWidgetItem(str(rs_nota[5]))
        bimestre2= QTableWidgetItem(str(rs_nota[6]))
        bimestre3= QTableWidgetItem(str(rs_nota[7]))
        bimestre4= QTableWidgetItem(str(rs_nota[8]))
        parcial_b1= QTableWidgetItem(str(rs_nota[9]))
        parcial_b2= QTableWidgetItem(str(rs_nota[10]))
        parcial_b3= QTableWidgetItem(str(rs_nota[11]))
        parcial_b4= QTableWidgetItem(str(rs_nota[12]))
        prom1=(str(round(int((rs_nota[1]+rs_nota[5]+rs_nota[9])/3))))
        prom2=(str(round(int((rs_nota[2]+rs_nota[6]+rs_nota[10])/3))))
        prom3=(str(round(int((rs_nota[3]+rs_nota[7]+rs_nota[11])/3))))
        prom4=(str(round(int((rs_nota[4]+rs_nota[8]+rs_nota[12])/3))))
        entrar.tableWidget_5.setItem(0,0,tarea_b1)
        entrar.tableWidget_5.setItem(0,1,tarea_b2)
        entrar.tableWidget_5.setItem(0,2,tarea_b3)
        entrar.tableWidget_5.setItem(0,3,tarea_b4)
        entrar.tableWidget_5.setItem(1,0,parcial_b1)
        entrar.tableWidget_5.setItem(1,1,parcial_b2)
        entrar.tableWidget_5.setItem(1,2,parcial_b3)
        entrar.tableWidget_5.setItem(1,3,parcial_b4)
        entrar.tableWidget_5.setItem(2,0,bimestre1)
        entrar.tableWidget_5.setItem(2,1,bimestre2)
        entrar.tableWidget_5.setItem(2,2,bimestre3)
        entrar.tableWidget_5.setItem(2,3,bimestre4)
        entrar.tableWidget_5.setItem(2,3,bimestre4)
        entrar.tableWidget_5.setItem(2,3,bimestre4)
        entrar.tableWidget_5.setItem(2,3,bimestre4)
        entrar.tableWidget_5.setItem(2,3,bimestre4)
        entrar.tableWidget_5.setItem(2,3,bimestre4)
        entrar.tableWidget_5.setItem(3,0,QTableWidgetItem(prom1))
        entrar.tableWidget_5.setItem(3,1,QTableWidgetItem(prom2))
        entrar.tableWidget_5.setItem(3,2,QTableWidgetItem(prom3))
        entrar.tableWidget_5.setItem(3,3,QTableWidgetItem(prom4))
        entrar.tableWidget_5.setItem(3,4,QTableWidgetItem(str(round((int(prom1)+int(prom2)+int(prom3)+int(prom4))/4))))
        row+=1
def mostrar_nota_cien(rs_nota):
    row=0
    while(row<4):
        tarea_b1=QTableWidgetItem(str(rs_nota[1]))
        tarea_b2=QTableWidgetItem(str(rs_nota[2]))
        tarea_b3= QTableWidgetItem(str(rs_nota[3]))
        tarea_b4= QTableWidgetItem(str(rs_nota[4]))
        bimestre1= QTableWidgetItem(str(rs_nota[5]))
        bimestre2= QTableWidgetItem(str(rs_nota[6]))
        bimestre3= QTableWidgetItem(str(rs_nota[7]))
        bimestre4= QTableWidgetItem(str(rs_nota[8]))
        parcial_b1= QTableWidgetItem(str(rs_nota[9]))
        parcial_b2= QTableWidgetItem(str(rs_nota[10]))
        parcial_b3= QTableWidgetItem(str(rs_nota[11]))
        parcial_b4= QTableWidgetItem(str(rs_nota[12]))
        prom1=(str(round(int((rs_nota[1]+rs_nota[5]+rs_nota[9])/3))))
        prom2=(str(round(int((rs_nota[2]+rs_nota[6]+rs_nota[10])/3))))
        prom3=(str(round(int((rs_nota[3]+rs_nota[7]+rs_nota[11])/3))))
        prom4=(str(round(int((rs_nota[4]+rs_nota[8]+rs_nota[12])/3))))
        entrar.tableWidget_4.setItem(0,0,tarea_b1)
        entrar.tableWidget_4.setItem(0,1,tarea_b2)
        entrar.tableWidget_4.setItem(0,2,tarea_b3)
        entrar.tableWidget_4.setItem(0,3,tarea_b4)
        entrar.tableWidget_4.setItem(1,0,parcial_b1)
        entrar.tableWidget_4.setItem(1,1,parcial_b2)
        entrar.tableWidget_4.setItem(1,2,parcial_b3)
        entrar.tableWidget_4.setItem(1,3,parcial_b4)
        entrar.tableWidget_4.setItem(2,0,bimestre1)
        entrar.tableWidget_4.setItem(2,1,bimestre2)
        entrar.tableWidget_4.setItem(2,2,bimestre3)
        entrar.tableWidget_4.setItem(2,3,bimestre4)
        entrar.tableWidget_4.setItem(2,3,bimestre4)
        entrar.tableWidget_4.setItem(2,3,bimestre4)
        entrar.tableWidget_4.setItem(2,3,bimestre4)
        entrar.tableWidget_4.setItem(2,3,bimestre4)
        entrar.tableWidget_4.setItem(2,3,bimestre4)
        entrar.tableWidget_4.setItem(3,0,QTableWidgetItem(prom1))
        entrar.tableWidget_4.setItem(3,1,QTableWidgetItem(prom2))
        entrar.tableWidget_4.setItem(3,2,QTableWidgetItem(prom3))
        entrar.tableWidget_4.setItem(3,3,QTableWidgetItem(prom4))
        entrar.tableWidget_4.setItem(3,4,QTableWidgetItem(str(round((int(prom1)+int(prom2)+int(prom3)+int(prom4))/4))))
        row+=1
# NO ABRIR X2
def mostrar_nota_mate_tutor(rs_nota):
    row=0
    while(row<4):
        tarea_b1=QTableWidgetItem(str(rs_nota[1]))
        tarea_b2=QTableWidgetItem(str(rs_nota[2]))
        tarea_b3= QTableWidgetItem(str(rs_nota[3]))
        tarea_b4= QTableWidgetItem(str(rs_nota[4]))
        bimestre1= QTableWidgetItem(str(rs_nota[5]))
        bimestre2= QTableWidgetItem(str(rs_nota[6]))
        bimestre3= QTableWidgetItem(str(rs_nota[7]))
        bimestre4= QTableWidgetItem(str(rs_nota[8]))
        parcial_b1= QTableWidgetItem(str(rs_nota[9]))
        parcial_b2= QTableWidgetItem(str(rs_nota[10]))
        parcial_b3= QTableWidgetItem(str(rs_nota[11]))
        parcial_b4= QTableWidgetItem(str(rs_nota[12]))
        prom1=(str(round(int((rs_nota[1]+rs_nota[5]+rs_nota[9])/3))))
        prom2=(str(round(int((rs_nota[2]+rs_nota[6]+rs_nota[10])/3))))
        prom3=(str(round(int((rs_nota[3]+rs_nota[7]+rs_nota[11])/3))))
        prom4=(str(round(int((rs_nota[4]+rs_nota[8]+rs_nota[12])/3))))
        entrar_tutor.tableWidget_6.setItem(0,0,tarea_b1)
        entrar_tutor.tableWidget_6.setItem(0,1,tarea_b2)
        entrar_tutor.tableWidget_6.setItem(0,2,tarea_b3)
        entrar_tutor.tableWidget_6.setItem(0,3,tarea_b4)
        entrar_tutor.tableWidget_6.setItem(1,0,parcial_b1)
        entrar_tutor.tableWidget_6.setItem(1,1,parcial_b2)
        entrar_tutor.tableWidget_6.setItem(1,2,parcial_b3)
        entrar_tutor.tableWidget_6.setItem(1,3,parcial_b4)
        entrar_tutor.tableWidget_6.setItem(2,0,bimestre1)
        entrar_tutor.tableWidget_6.setItem(2,1,bimestre2)
        entrar_tutor.tableWidget_6.setItem(2,2,bimestre3)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(3,0,QTableWidgetItem(prom1))
        entrar_tutor.tableWidget_6.setItem(3,1,QTableWidgetItem(prom2))
        entrar_tutor.tableWidget_6.setItem(3,2,QTableWidgetItem(prom3))
        entrar_tutor.tableWidget_6.setItem(3,3,QTableWidgetItem(prom4))
        entrar_tutor.tableWidget_6.setItem(3,4,QTableWidgetItem(str(round((int(prom1)+int(prom2)+int(prom3)+int(prom4))/4))))
        row+=1
def mostrar_nota_ed_tutor(rs_nota):
    row=0
    while(row<4):
        tarea_b1=QTableWidgetItem(str(rs_nota[1]))
        tarea_b2=QTableWidgetItem(str(rs_nota[2]))
        tarea_b3= QTableWidgetItem(str(rs_nota[3]))
        tarea_b4= QTableWidgetItem(str(rs_nota[4]))
        bimestre1= QTableWidgetItem(str(rs_nota[5]))
        bimestre2= QTableWidgetItem(str(rs_nota[6]))
        bimestre3= QTableWidgetItem(str(rs_nota[7]))
        bimestre4= QTableWidgetItem(str(rs_nota[8]))
        parcial_b1= QTableWidgetItem(str(rs_nota[9]))
        parcial_b2= QTableWidgetItem(str(rs_nota[10]))
        parcial_b3= QTableWidgetItem(str(rs_nota[11]))
        parcial_b4= QTableWidgetItem(str(rs_nota[12]))
        prom1=(str(round(int((rs_nota[1]+rs_nota[5]+rs_nota[9])/3))))
        prom2=(str(round(int((rs_nota[2]+rs_nota[6]+rs_nota[10])/3))))
        prom3=(str(round(int((rs_nota[3]+rs_nota[7]+rs_nota[11])/3))))
        prom4=(str(round(int((rs_nota[4]+rs_nota[8]+rs_nota[12])/3))))
        entrar_tutor.tableWidget_6.setItem(0,0,tarea_b1)
        entrar_tutor.tableWidget_6.setItem(0,1,tarea_b2)
        entrar_tutor.tableWidget_6.setItem(0,2,tarea_b3)
        entrar_tutor.tableWidget_6.setItem(0,3,tarea_b4)
        entrar_tutor.tableWidget_6.setItem(1,0,parcial_b1)
        entrar_tutor.tableWidget_6.setItem(1,1,parcial_b2)
        entrar_tutor.tableWidget_6.setItem(1,2,parcial_b3)
        entrar_tutor.tableWidget_6.setItem(1,3,parcial_b4)
        entrar_tutor.tableWidget_6.setItem(2,0,bimestre1)
        entrar_tutor.tableWidget_6.setItem(2,1,bimestre2)
        entrar_tutor.tableWidget_6.setItem(2,2,bimestre3)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(3,0,QTableWidgetItem(prom1))
        entrar_tutor.tableWidget_6.setItem(3,1,QTableWidgetItem(prom2))
        entrar_tutor.tableWidget_6.setItem(3,2,QTableWidgetItem(prom3))
        entrar_tutor.tableWidget_6.setItem(3,3,QTableWidgetItem(prom4))
        entrar_tutor.tableWidget_6.setItem(3,4,QTableWidgetItem(str(round((int(prom1)+int(prom2)+int(prom3)+int(prom4))/4))))
        row+=1
def mostrar_nota_tuto_tutor(rs_nota):
    row=0
    while(row<4):
        tarea_b1=QTableWidgetItem(str(rs_nota[1]))
        tarea_b2=QTableWidgetItem(str(rs_nota[2]))
        tarea_b3= QTableWidgetItem(str(rs_nota[3]))
        tarea_b4= QTableWidgetItem(str(rs_nota[4]))
        bimestre1= QTableWidgetItem(str(rs_nota[5]))
        bimestre2= QTableWidgetItem(str(rs_nota[6]))
        bimestre3= QTableWidgetItem(str(rs_nota[7]))
        bimestre4= QTableWidgetItem(str(rs_nota[8]))
        parcial_b1= QTableWidgetItem(str(rs_nota[9]))
        parcial_b2= QTableWidgetItem(str(rs_nota[10]))
        parcial_b3= QTableWidgetItem(str(rs_nota[11]))
        parcial_b4= QTableWidgetItem(str(rs_nota[12]))
        prom1=(str(round(int((rs_nota[1]+rs_nota[5]+rs_nota[9])/3))))
        prom2=(str(round(int((rs_nota[2]+rs_nota[6]+rs_nota[10])/3))))
        prom3=(str(round(int((rs_nota[3]+rs_nota[7]+rs_nota[11])/3))))
        prom4=(str(round(int((rs_nota[4]+rs_nota[8]+rs_nota[12])/3))))
        entrar_tutor.tableWidget_6.setItem(0,0,tarea_b1)
        entrar_tutor.tableWidget_6.setItem(0,1,tarea_b2)
        entrar_tutor.tableWidget_6.setItem(0,2,tarea_b3)
        entrar_tutor.tableWidget_6.setItem(0,3,tarea_b4)
        entrar_tutor.tableWidget_6.setItem(1,0,parcial_b1)
        entrar_tutor.tableWidget_6.setItem(1,1,parcial_b2)
        entrar_tutor.tableWidget_6.setItem(1,2,parcial_b3)
        entrar_tutor.tableWidget_6.setItem(1,3,parcial_b4)
        entrar_tutor.tableWidget_6.setItem(2,0,bimestre1)
        entrar_tutor.tableWidget_6.setItem(2,1,bimestre2)
        entrar_tutor.tableWidget_6.setItem(2,2,bimestre3)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(3,0,QTableWidgetItem(prom1))
        entrar_tutor.tableWidget_6.setItem(3,1,QTableWidgetItem(prom2))
        entrar_tutor.tableWidget_6.setItem(3,2,QTableWidgetItem(prom3))
        entrar_tutor.tableWidget_6.setItem(3,3,QTableWidgetItem(prom4))
        entrar_tutor.tableWidget_6.setItem(3,4,QTableWidgetItem(str(round((int(prom1)+int(prom2)+int(prom3)+int(prom4))/4))))
        row+=1
def mostrar_nota_comu_tutor(rs_nota):
    row=0
    while(row<4):
        tarea_b1=QTableWidgetItem(str(rs_nota[1]))
        tarea_b2=QTableWidgetItem(str(rs_nota[2]))
        tarea_b3= QTableWidgetItem(str(rs_nota[3]))
        tarea_b4= QTableWidgetItem(str(rs_nota[4]))
        bimestre1= QTableWidgetItem(str(rs_nota[5]))
        bimestre2= QTableWidgetItem(str(rs_nota[6]))
        bimestre3= QTableWidgetItem(str(rs_nota[7]))
        bimestre4= QTableWidgetItem(str(rs_nota[8]))
        parcial_b1= QTableWidgetItem(str(rs_nota[9]))
        parcial_b2= QTableWidgetItem(str(rs_nota[10]))
        parcial_b3= QTableWidgetItem(str(rs_nota[11]))
        parcial_b4= QTableWidgetItem(str(rs_nota[12]))
        prom1=(str(round(int((rs_nota[1]+rs_nota[5]+rs_nota[9])/3))))
        prom2=(str(round(int((rs_nota[2]+rs_nota[6]+rs_nota[10])/3))))
        prom3=(str(round(int((rs_nota[3]+rs_nota[7]+rs_nota[11])/3))))
        prom4=(str(round(int((rs_nota[4]+rs_nota[8]+rs_nota[12])/3))))
        entrar_tutor.tableWidget_6.setItem(0,0,tarea_b1)
        entrar_tutor.tableWidget_6.setItem(0,1,tarea_b2)
        entrar_tutor.tableWidget_6.setItem(0,2,tarea_b3)
        entrar_tutor.tableWidget_6.setItem(0,3,tarea_b4)
        entrar_tutor.tableWidget_6.setItem(1,0,parcial_b1)
        entrar_tutor.tableWidget_6.setItem(1,1,parcial_b2)
        entrar_tutor.tableWidget_6.setItem(1,2,parcial_b3)
        entrar_tutor.tableWidget_6.setItem(1,3,parcial_b4)
        entrar_tutor.tableWidget_6.setItem(2,0,bimestre1)
        entrar_tutor.tableWidget_6.setItem(2,1,bimestre2)
        entrar_tutor.tableWidget_6.setItem(2,2,bimestre3)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(3,0,QTableWidgetItem(prom1))
        entrar_tutor.tableWidget_6.setItem(3,1,QTableWidgetItem(prom2))
        entrar_tutor.tableWidget_6.setItem(3,2,QTableWidgetItem(prom3))
        entrar_tutor.tableWidget_6.setItem(3,3,QTableWidgetItem(prom4))
        entrar_tutor.tableWidget_6.setItem(3,4,QTableWidgetItem(str(round((int(prom1)+int(prom2)+int(prom3)+int(prom4))/4))))
        row+=1
def mostrar_nota_cien_tutor(rs_nota):
    row=0
    while(row<4):
        tarea_b1=QTableWidgetItem(str(rs_nota[1]))
        tarea_b2=QTableWidgetItem(str(rs_nota[2]))
        tarea_b3= QTableWidgetItem(str(rs_nota[3]))
        tarea_b4= QTableWidgetItem(str(rs_nota[4]))
        bimestre1= QTableWidgetItem(str(rs_nota[5]))
        bimestre2= QTableWidgetItem(str(rs_nota[6]))
        bimestre3= QTableWidgetItem(str(rs_nota[7]))
        bimestre4= QTableWidgetItem(str(rs_nota[8]))
        parcial_b1= QTableWidgetItem(str(rs_nota[9]))
        parcial_b2= QTableWidgetItem(str(rs_nota[10]))
        parcial_b3= QTableWidgetItem(str(rs_nota[11]))
        parcial_b4= QTableWidgetItem(str(rs_nota[12]))
        prom1=(str(round(int((rs_nota[1]+rs_nota[5]+rs_nota[9])/3))))
        prom2=(str(round(int((rs_nota[2]+rs_nota[6]+rs_nota[10])/3))))
        prom3=(str(round(int((rs_nota[3]+rs_nota[7]+rs_nota[11])/3))))
        prom4=(str(round(int((rs_nota[4]+rs_nota[8]+rs_nota[12])/3))))
        entrar_tutor.tableWidget_6.setItem(0,0,tarea_b1)
        entrar_tutor.tableWidget_6.setItem(0,1,tarea_b2)
        entrar_tutor.tableWidget_6.setItem(0,2,tarea_b3)
        entrar_tutor.tableWidget_6.setItem(0,3,tarea_b4)
        entrar_tutor.tableWidget_6.setItem(1,0,parcial_b1)
        entrar_tutor.tableWidget_6.setItem(1,1,parcial_b2)
        entrar_tutor.tableWidget_6.setItem(1,2,parcial_b3)
        entrar_tutor.tableWidget_6.setItem(1,3,parcial_b4)
        entrar_tutor.tableWidget_6.setItem(2,0,bimestre1)
        entrar_tutor.tableWidget_6.setItem(2,1,bimestre2)
        entrar_tutor.tableWidget_6.setItem(2,2,bimestre3)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(2,3,bimestre4)
        entrar_tutor.tableWidget_6.setItem(3,0,QTableWidgetItem(prom1))
        entrar_tutor.tableWidget_6.setItem(3,1,QTableWidgetItem(prom2))
        entrar_tutor.tableWidget_6.setItem(3,2,QTableWidgetItem(prom3))
        entrar_tutor.tableWidget_6.setItem(3,3,QTableWidgetItem(prom4))
        entrar_tutor.tableWidget_6.setItem(3,4,QTableWidgetItem(str(round((int(prom1)+int(prom2)+int(prom3)+int(prom4))/4))))
        row+=1

def gui_entrar_tutor(result):
    login.hide()
    entrar_tutor.show()
    entrar_tutor.label.setText(("Bienvenido tutor "+result[1]+" "+result[2]+"-"+result[3]).upper())
    rs_alumnos=db.mostrar_alumnos(result[3])
    mostrar_alumnos(rs_alumnos)
    rs_reportes=db.mostrar_reportes_tutor(result[3])
    mostrar_reportes_tutor(rs_reportes)
    entrar_tutor.pushButton_6.clicked.connect(generar_reporte)
    entrar_tutor.pushButton_7.clicked.connect(generar_nota)
    entrar_tutor.pushButton_8.clicked.connect(buscar_notas)

def mostrar_alumnos(rs_alumnos):
    row=0
    while(row<len(rs_alumnos)):
        entrar_tutor.tableWidget.insertRow(row)
        nombre=QTableWidgetItem(str(rs_alumnos[row][1]))
        apellido=QTableWidgetItem(rs_alumnos[row][2])
        correo=QTableWidgetItem(rs_alumnos[row][3])
        entrar_tutor.tableWidget.setItem(row,0,nombre)
        entrar_tutor.tableWidget.setItem(row,1,apellido)
        entrar_tutor.tableWidget.setItem(row,2,correo)
        row+=1

def mostrar_reportes_tutor(rs_reportes):
    row=0
    while(row<len(rs_reportes)):
        entrar_tutor.tableWidget_2.insertRow(row)
        nombre=QTableWidgetItem(rs_reportes[row][0]+" "+rs_reportes[row][1])
        reporte=QTableWidgetItem(rs_reportes[row][2])
        fecha=QTableWidgetItem(str(rs_reportes[row][3]))
        entrar_tutor.tableWidget_2.setItem(row,0,nombre)
        entrar_tutor.tableWidget_2.setItem(row,1,reporte)
        entrar_tutor.tableWidget_2.setItem(row,2,fecha)
        row+=1

def generar_reporte(result):
    try:
        nombre=entrar_tutor.lineEdit.text()
        apellido=entrar_tutor.lineEdit_2.text()
        rs_buscar=db.buscar_alumno(nombre, apellido)
        comentario=entrar_tutor.lineEdit_3.text()
        fecha=datetime.datetime.now().strftime("%Y-%m-%d")
        db.registro_reporte(comentario, fecha, rs_buscar[0])
    except:
        msg_error("ERROR", "No se encontró el alumno")   
    else:
        entrar_tutor.lineEdit.setText("")
        entrar_tutor.lineEdit_2.setText("")
        entrar_tutor.lineEdit_3.setText("")
        msg_about("Éxito", "Reporte registado con correctamente")

def generar_nota(result):
    try:
        nombre=entrar_tutor.lineEdit_4.text()
        apellido=entrar_tutor.lineEdit_5.text()
        curso=entrar_tutor.comboBox.currentText()
        rs_buscar=db.buscar_alumno(nombre, apellido)
        tarea_b1=int(entrar_tutor.tableWidget_6.item(0,0).text())
        tarea_b2=int(entrar_tutor.tableWidget_6.item(0,1).text())
        tarea_b3=int(entrar_tutor.tableWidget_6.item(0,2).text())
        tarea_b4=int(entrar_tutor.tableWidget_6.item(0,3).text())
        parcial_b1=int(entrar_tutor.tableWidget_6.item(1,0).text())
        parcial_b2=int(entrar_tutor.tableWidget_6.item(1,1).text())
        parcial_b3=int(entrar_tutor.tableWidget_6.item(1,2).text())
        parcial_b4=int(entrar_tutor.tableWidget_6.item(1,3).text())
        bimestre1=int(entrar_tutor.tableWidget_6.item(2,0).text())
        bimestre2=int(entrar_tutor.tableWidget_6.item(2,1).text())
        bimestre3=int(entrar_tutor.tableWidget_6.item(2,2).text())
        bimestre4=int(entrar_tutor.tableWidget_6.item(2,3).text())
        db.registrar_nota(bimestre1,bimestre2,bimestre3,bimestre4,parcial_b1,parcial_b2,parcial_b3,parcial_b4,tarea_b1,tarea_b2,tarea_b3,tarea_b4,rs_buscar[0], curso)       
    except Exception as e:
        print(e)
        msg_error("ERROR", "No se encontró el alumno")
    else:
        entrar_tutor.lineEdit_4.setText("")
        entrar_tutor.lineEdit_5.setText("")
        msg_about("Éxito", "Notas registadas correctamente")

def buscar_notas(result):
    try:
        nombre=entrar_tutor.lineEdit_4.text()
        apellido=entrar_tutor.lineEdit_5.text()
        curso=entrar_tutor.comboBox.currentText()
        rs_buscar=db.buscar_alumno(nombre, apellido)
        if(curso=='Matemática'):
            rs_nota_mate=db.mostrar_notas(rs_buscar[0],"Matemática")
            mostrar_nota_mate_tutor(rs_nota_mate)
        elif(curso=='Comunicación'):
            rs_nota_comu=db.mostrar_notas(rs_buscar[0],"Comunicación")
            mostrar_nota_comu_tutor(rs_nota_comu)
        elif(curso=='Ciencias'):
            rs_nota_cien=db.mostrar_notas(rs_buscar[0],"Ciencias")
            mostrar_nota_cien_tutor(rs_nota_cien)
        elif(curso=='Educación Física'):
            rs_nota_ed=db.mostrar_notas(rs_buscar[0],"Educación Física")
            mostrar_nota_ed_tutor(rs_nota_ed)
        elif(curso=='Tutoría'):
            rs_nota_tuto=db.mostrar_notas(rs_buscar[0],"Tutoría")
            mostrar_nota_tuto_tutor(rs_nota_tuto)
    except Exception as e:
        print(e)
        msg_error("ERROR", "No se encontró el alumno")
    else:
        msg_about("Éxito", "Notas de alumno encontradas correctamente")

def gui_volver_login():
    registro.hide()
    registro_tutor.hide()
    login.label_4.setText("")
    login.show()

def gui_registro_tutor():
    login.hide()
    registro_tutor.show()
    
def datos_alumno():
    nombre = registro.lineEdit.text()
    apellido = registro.lineEdit_2.text()
    correo = registro.lineEdit_3.text()
    aula = registro.comboBox.currentText()
    contraseña = registro.lineEdit_5.text()

    if len(nombre) == 0 or len(apellido) == 0 or len(correo) == 0:
        msg_error("","Complete todos los campos")
    elif len(contraseña) <= 6:
        msg_error("ERROR", "La contraseña debe tener como mínimo 7 dígitos")

    else:
        db.registro_alumno(nombre, apellido, correo, contraseña, aula)
        msg_about("Éxito", "Se ha registrado al alumno correctamente")
        registro.lineEdit.setText("")
        registro.lineEdit_2.setText("")
        registro.lineEdit_3.setText("")
        registro.lineEdit_5.setText("")

def datos_tutor():
    nombre = registro_tutor.lineEdit.text()
    apellido = registro_tutor.lineEdit_2.text()
    correo = registro_tutor.lineEdit_3.text()
    aula = registro_tutor.comboBox.currentText()
    contraseña = registro_tutor.lineEdit_5.text()

    if len(nombre) == 0 or len(apellido) == 0 or len(correo) == 0:
        msg_error("","Complete todos los campos")
    elif len(contraseña) <= 6:
        msg_error("ERROR", "La contraseña debe tener como mínimo 7 dígitos")

    else:
        db.registro_tutor(nombre, apellido, aula, correo, contraseña)
        msg_about("Éxito", "Se ha registrado al tutor correctamente")
        registro_tutor.lineEdit.setText("")
        registro_tutor.lineEdit_2.setText("")
        registro_tutor.lineEdit_3.setText("")
        registro_tutor.lineEdit_5.setText("")

def cerrar():
    app.exit()

#NO ABRIR XD
def imprimir_notas():
    try:
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Times", size=10)
        line_height = pdf.font_size * 2.5
        col_width = pdf.epw / 6 
        pdf.write(30, "Reporte de notas \n")
        pdf.write(25, "Matemáticas\n")
        pdf.cell(col_width, line_height, txt=" ", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 1", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 2", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 3", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 4", border=1)
        pdf.cell(col_width, line_height, txt="FINAL", border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Tareas",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(0,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(0,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(0,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(0,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Examen mensual",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(1,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(1,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(1,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(1,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Examen bimestral",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(2,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(2,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(2,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(2,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Promedio",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(3,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(3,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(3,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(3,3).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_3.item(3,4).text(),border=1)
        pdf.ln(line_height)
        pdf.ln(line_height)
        pdf.write(25, "Comunicación\n")
        pdf.cell(col_width, line_height, txt=" ", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 1", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 2", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 3", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 4", border=1)
        pdf.cell(col_width, line_height, txt="FINAL", border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Tareas",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(0,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(0,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(0,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(0,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Examen mensual",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(1,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(1,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(1,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(1,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Examen bimestral",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(2,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(2,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(2,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(2,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Promedio",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(3,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(3,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(3,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(3,3).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_5.item(3,4).text(),border=1)
        pdf.ln(line_height)
        pdf.ln(line_height)
        pdf.write(25, "Ciencias\n")
        pdf.cell(col_width, line_height, txt=" ", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 1", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 2", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 3", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 4", border=1)
        pdf.cell(col_width, line_height, txt="FINAL", border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Tareas",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(0,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(0,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(0,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(0,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Examen mensual",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(1,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(1,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(1,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(1,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Examen bimestral",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(2,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(2,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(2,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(2,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Promedio",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(3,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(3,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(3,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(3,3).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_4.item(3,4).text(),border=1)
        pdf.ln(line_height)
        pdf.ln(line_height)
        pdf.write(25, "Tutoría\n")
        pdf.cell(col_width, line_height, txt=" ", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 1", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 2", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 3", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 4", border=1)
        pdf.cell(col_width, line_height, txt="FINAL", border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Tareas",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(0,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(0,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(0,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(0,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Examen mensual",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(1,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(1,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(1,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(1,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Examen bimestral",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(2,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(2,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(2,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(2,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Promedio",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(3,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(3,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(3,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(3,3).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_7.item(3,4).text(),border=1)
        pdf.ln(line_height)
        pdf.ln(line_height)
        pdf.write(25, "Educación Física\n")
        pdf.cell(col_width, line_height, txt=" ", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 1", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 2", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 3", border=1)
        pdf.cell(col_width, line_height, txt="Bimestre 4", border=1)
        pdf.cell(col_width, line_height, txt="FINAL", border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Tareas",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(0,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(0,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(0,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(0,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Examen mensual",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(1,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(1,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(1,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(1,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Examen bimestral",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(2,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(2,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(2,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(2,3).text(),border=1)
        pdf.ln(line_height)
        pdf.cell(col_width,line_height,"Promedio",border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(3,0).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(3,1).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(3,2).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(3,3).text(),border=1)
        pdf.cell(col_width,line_height,entrar.tableWidget_6.item(3,4).text(),border=1)
        pdf.ln(line_height)
        pdf.output('../Reporte_Notas.pdf')
    except Exception as e:
        print(e)
        print("Error al generar el reporte")
    else:
        msg_about("Éxito", "Reporte descargado correctamente, busca en tu escritorio el archivo Reporte_Notas.pdf")

def bloquear_tablas():
    entrar.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    entrar.tableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    entrar.tableWidget_4.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    entrar.tableWidget_5.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    entrar.tableWidget_6.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    entrar.tableWidget_7.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    entrar_tutor.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    entrar_tutor.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

bloquear_tablas()

login.pushButton.clicked.connect(gui_login)
login.pushButton_2.clicked.connect(gui_registro_alumno)    
login.pushButton_4.clicked.connect(gui_registro_tutor)

registro.pushButton.clicked.connect(datos_alumno)
registro.pushButton.clicked.connect(gui_registro_alumno)
registro.pushButton_3.clicked.connect(gui_volver_login)

registro_tutor.pushButton_3.clicked.connect(datos_tutor)
registro_tutor.pushButton_3.clicked.connect(gui_registro_tutor)
registro_tutor.pushButton_2.clicked.connect(gui_volver_login)

entrar.pushButton_2.clicked.connect(lambda: entrar.stackedWidget.setCurrentWidget(entrar.page_asistencia))
entrar.pushButton_3.clicked.connect(lambda: entrar.stackedWidget.setCurrentWidget(entrar.page_cursos))
entrar.pushButton_8.clicked.connect(lambda: entrar.stackedWidget.setCurrentWidget(entrar.page_mate))
entrar.pushButton_9.clicked.connect(lambda: entrar.stackedWidget.setCurrentWidget(entrar.page_ciencias))
entrar.pushButton_10.clicked.connect(lambda: entrar.stackedWidget.setCurrentWidget(entrar.page_comu))
entrar.pushButton_11.clicked.connect(lambda: entrar.stackedWidget.setCurrentWidget(entrar.page_EF))
entrar.pushButton_12.clicked.connect(lambda: entrar.stackedWidget.setCurrentWidget(entrar.page_Tuto))
entrar.pushButton_4.clicked.connect(lambda: entrar.stackedWidget.setCurrentWidget(entrar.page_reportes))
entrar.pushButton_5.clicked.connect(cerrar_sesion)

entrar_tutor.pushButton_2.clicked.connect(lambda: entrar_tutor.stackedWidget.setCurrentWidget(entrar_tutor.page))
entrar_tutor.pushButton_3.clicked.connect(lambda: entrar_tutor.stackedWidget.setCurrentWidget(entrar_tutor.page_2))
entrar_tutor.pushButton_4.clicked.connect(lambda: entrar_tutor.stackedWidget.setCurrentWidget(entrar_tutor.page_3))
entrar_tutor.pushButton_9.clicked.connect(lambda: entrar_tutor.stackedWidget.setCurrentWidget(entrar_tutor.page_4))


entrar_tutor.pushButton_5.clicked.connect(cerrar_sesion)

login.show()
app.exec_()
